feat: upvote logic
opengovsg/spotlightsg pull request #99
Opened 2022-01-25 09:13 UTC by JeraldYik

## Context

Add upvote/undo upvote logic. Composite unique constraint added to foreign keys `postId` and `userId`.

Routes:
- `POST /upvote` (upvote)
- `DELETE /upvote` (undo upvote)

## Tests

- [x] Upvote a post
- [x] Try following the same post again, should throw a 400 error
- [x] Call `GET /posts` and `GET /posts/:id`. Check the new `upvoteCount: 1` attribute 
- [x] Undo upvote this post  
- [x] Call `GET /posts` and `GET /posts/:id`. Check `upvoteCount: 0`

2022-01-25 09:19 UTC, JeraldYik commented on backend/src/posts/posts.service.ts
> +      upvoteCount: model.upvotes.filter((upvote) => upvote.postId === model.id)
just want to put it out here. is filtering necessary for tables joined using eager loading? should i just do a simple `model.upvotes.length` ?

2022-01-25 09:19 UTC, JeraldYik commented on backend/src/posts/posts.service.ts
> +        upvoteCount: post.upvotes.filter((upvote) => upvote.postId === post.id)
similar to above comment

2022-01-25 18:52 UTC, JasonChong96 requested changes

2022-01-25 18:54 UTC, JasonChong96 requested changes

2022-01-25 18:54 UTC, JasonChong96 commented on backend/src/posts/posts.service.ts
> +        upvoteCount: post.upvoteCount,
Also we need an `isUpvoted` (or a better name) similar to `isFollowing`. This is to allow the frontend to know if the current user has already upvoted this post

2022-01-26 07:37 UTC, JeraldYik commented on backend/src/posts/posts.service.ts
> +        upvoteCount: post.upvoteCount,
[commit](https://github.com/opengovsg/spotlightsg/pull/99/commits/edd74f4f2007d673fffa3befbe83b8e49360b78e). named it `hasBeenUpvoted`

2022-01-26 07:38 UTC, JeraldYik commented on backend/src/posts/posts.service.ts
> +      upvoteCount: model.upvotes.filter((upvote) => upvote.postId === model.id)
[commit](https://github.com/opengovsg/spotlightsg/pull/99/commits/edd74f4f2007d673fffa3befbe83b8e49360b78e)

2022-01-26 07:38 UTC, JeraldYik commented on backend/src/posts/posts.service.ts
> +        upvoteCount: post.upvotes.filter((upvote) => upvote.postId === post.id)
resolved with comment above

2022-01-27 06:24 UTC, JasonChong96 approved these changes
lgtm

2022-01-27 07:57 UTC, merged